commit_message: '[ci skip]'
files:
  - source: /src/main/resources/i18n/strings.properties
    translation: /src/main/resources/i18n/strings_%two_letters_code%.properties
    escape_quotes: 0
    escape_special_characters: 0
